# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Gatsby

on:
  pull_request:
    branches: [ main, new-new ]
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat ./.nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Use Node + Yarn
      uses: actions/setup-node@v3
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: "yarn"
    - run: yarn install --frozen-lockfile -std=c++17
    - if: github.event_name == 'push'
      run: npm run build --if-present
    - if: github.event_name == 'pull_request'
      run: npm run build:prefixed
      env:
        GATSBY_BRANCH: ${{ github.head_ref }}
    - name: "Set up security.txt and .well-known/security.txt"
      run: |
         mkdir public/.well-known
         cp security.txt public/security.txt
         cp security.txt public/.well-known/security.txt
    # A push event is a main merge; deploy to primary bucket.
    - if: github.event_name == 'push'
      name: Deploy Master to GCP
      uses: thesis/gcp-storage-bucket-action@v3.1.0
      with:
        service-key: ${{ secrets.TBTC_NETWORK_UPLOADER_SERVICE_KEY_JSON }}
        project: tbtc-prod
        bucket-name: tbtc.network
        build-folder: public
    # A pull_request event is a PR; deploy to preview bucket.
    - if: github.event_name == 'pull_request'
      name: Deploy PR to GCP
      uses: thesis/gcp-storage-bucket-action@v3.1.0
      with:
        service-key: ${{ secrets.TBTC_NETWORK_UPLOADER_SERVICE_KEY_JSON }}
        project: tbtc-prod
        bucket-name: preview.tbtc.network
        bucket-path: ${{ github.head_ref }}
        build-folder: public
    # A pull_request event is a PR; leave a comment with the preview URL.
    - if: github.event_name == 'pull_request'
      name: Post preview URL to PR
      uses: actions/github-script@v3
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Preview uploaded to https://preview.tbtc.network/${{ github.head_ref }}/.'
          })
